from typing import Any, Protocol
from uuid import UUID

from app.domain.project import Project


class ProjectRepository(Protocol):
    async def create(self, project: Project, conn: Any = None) -> None: ...

    async def save(self, project: Project, conn: Any = None) -> None: ...

    async def get_by_id(self, project_id: UUID) -> Project | None: ...

    async def get_by_slug(self, slug: str) -> Project | None: ...

    async def exists_by_slug(self, slug: str) -> bool: ...

    async def delete(self, project_id: UUID, conn: Any = None) -> bool: ...

    async def list_by_owner(self, owner_id: UUID) -> list[Project]: ...
