# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: control_plane.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'control_plane.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x63ontrol_plane.proto\x12\x17\x62\x61\x63kify.controlplane.v1\"\'\n\x11GetProjectRequest\x12\x12\n\nproject_id\x18\x01 \x01(\t\"t\n\x12GetProjectResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0c\n\x04slug\x18\x03 \x01(\t\x12\x13\n\x0bschema_name\x18\x04 \x01(\t\x12\x10\n\x08owner_id\x18\x05 \x01(\t\x12\x0f\n\x07version\x18\x06 \x01(\x05\"-\n\x17GetProjectConfigRequest\x12\x12\n\nproject_id\x18\x01 \x01(\t\"w\n\x18GetProjectConfigResponse\x12\x12\n\nproject_id\x18\x01 \x01(\t\x12\x0c\n\x04slug\x18\x02 \x01(\t\x12\x13\n\x0bschema_name\x18\x03 \x01(\t\x12\x0f\n\x07version\x18\x04 \x01(\x05\x12\x13\n\x0b\x63onfig_json\x18\x05 \x01(\t2\xf5\x01\n\x13\x43ontrolPlaneService\x12\x65\n\nGetProject\x12*.backify.controlplane.v1.GetProjectRequest\x1a+.backify.controlplane.v1.GetProjectResponse\x12w\n\x10GetProjectConfig\x12\x30.backify.controlplane.v1.GetProjectConfigRequest\x1a\x31.backify.controlplane.v1.GetProjectConfigResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'control_plane_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETPROJECTREQUEST']._serialized_start=48
  _globals['_GETPROJECTREQUEST']._serialized_end=87
  _globals['_GETPROJECTRESPONSE']._serialized_start=89
  _globals['_GETPROJECTRESPONSE']._serialized_end=205
  _globals['_GETPROJECTCONFIGREQUEST']._serialized_start=207
  _globals['_GETPROJECTCONFIGREQUEST']._serialized_end=252
  _globals['_GETPROJECTCONFIGRESPONSE']._serialized_start=254
  _globals['_GETPROJECTCONFIGRESPONSE']._serialized_end=373
  _globals['_CONTROLPLANESERVICE']._serialized_start=376
  _globals['_CONTROLPLANESERVICE']._serialized_end=621
# @@protoc_insertion_point(module_scope)
