# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import control_plane_pb2 as control__plane__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in control_plane_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ControlPlaneServiceStub:
    """ControlPlaneService is the internal, service-to-service contract for
    reading project data. It is never exposed to end users directly —
    callers (e.g. the Auth Service) authenticate with the same shared
    internal key used by the HTTP internal endpoints, sent as the
    "x-internal-key" gRPC metadata entry.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetProject = channel.unary_unary(
                '/backify.controlplane.v1.ControlPlaneService/GetProject',
                request_serializer=control__plane__pb2.GetProjectRequest.SerializeToString,
                response_deserializer=control__plane__pb2.GetProjectResponse.FromString,
                _registered_method=True)
        self.GetProjectConfig = channel.unary_unary(
                '/backify.controlplane.v1.ControlPlaneService/GetProjectConfig',
                request_serializer=control__plane__pb2.GetProjectConfigRequest.SerializeToString,
                response_deserializer=control__plane__pb2.GetProjectConfigResponse.FromString,
                _registered_method=True)


class ControlPlaneServiceServicer:
    """ControlPlaneService is the internal, service-to-service contract for
    reading project data. It is never exposed to end users directly —
    callers (e.g. the Auth Service) authenticate with the same shared
    internal key used by the HTTP internal endpoints, sent as the
    "x-internal-key" gRPC metadata entry.
    """

    def GetProject(self, request, context):
        """GetProject returns identity/ownership metadata for a project.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProjectConfig(self, request, context):
        """GetProjectConfig returns the full runtime config (entities + modules)
        for a project. Config shape is intentionally untyped (JSON) because
        the field/entity schema is config-driven and evolves per project
        without requiring a proto contract change.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ControlPlaneServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetProject': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProject,
                    request_deserializer=control__plane__pb2.GetProjectRequest.FromString,
                    response_serializer=control__plane__pb2.GetProjectResponse.SerializeToString,
            ),
            'GetProjectConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProjectConfig,
                    request_deserializer=control__plane__pb2.GetProjectConfigRequest.FromString,
                    response_serializer=control__plane__pb2.GetProjectConfigResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'backify.controlplane.v1.ControlPlaneService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('backify.controlplane.v1.ControlPlaneService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ControlPlaneService:
    """ControlPlaneService is the internal, service-to-service contract for
    reading project data. It is never exposed to end users directly —
    callers (e.g. the Auth Service) authenticate with the same shared
    internal key used by the HTTP internal endpoints, sent as the
    "x-internal-key" gRPC metadata entry.
    """

    @staticmethod
    def GetProject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/backify.controlplane.v1.ControlPlaneService/GetProject',
            control__plane__pb2.GetProjectRequest.SerializeToString,
            control__plane__pb2.GetProjectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetProjectConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/backify.controlplane.v1.ControlPlaneService/GetProjectConfig',
            control__plane__pb2.GetProjectConfigRequest.SerializeToString,
            control__plane__pb2.GetProjectConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
