// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: control/v1/control.proto

package controlv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetProjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProjectRequest) Reset() {
	*x = GetProjectRequest{}
	mi := &file_control_v1_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProjectRequest) ProtoMessage() {}

func (x *GetProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_v1_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProjectRequest.ProtoReflect.Descriptor instead.
func (*GetProjectRequest) Descriptor() ([]byte, []int) {
	return file_control_v1_control_proto_rawDescGZIP(), []int{0}
}

func (x *GetProjectRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

type GetProjectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Project       *Project               `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"` // non-empty on failure
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProjectResponse) Reset() {
	*x = GetProjectResponse{}
	mi := &file_control_v1_control_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProjectResponse) ProtoMessage() {}

func (x *GetProjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_v1_control_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProjectResponse.ProtoReflect.Descriptor instead.
func (*GetProjectResponse) Descriptor() ([]byte, []int) {
	return file_control_v1_control_proto_rawDescGZIP(), []int{1}
}

func (x *GetProjectResponse) GetProject() *Project {
	if x != nil {
		return x.Project
	}
	return nil
}

func (x *GetProjectResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetProjectConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProjectConfigRequest) Reset() {
	*x = GetProjectConfigRequest{}
	mi := &file_control_v1_control_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProjectConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProjectConfigRequest) ProtoMessage() {}

func (x *GetProjectConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_v1_control_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProjectConfigRequest.ProtoReflect.Descriptor instead.
func (*GetProjectConfigRequest) Descriptor() ([]byte, []int) {
	return file_control_v1_control_proto_rawDescGZIP(), []int{2}
}

func (x *GetProjectConfigRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

type GetProjectConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *ProjectConfig         `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProjectConfigResponse) Reset() {
	*x = GetProjectConfigResponse{}
	mi := &file_control_v1_control_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProjectConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProjectConfigResponse) ProtoMessage() {}

func (x *GetProjectConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_v1_control_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProjectConfigResponse.ProtoReflect.Descriptor instead.
func (*GetProjectConfigResponse) Descriptor() ([]byte, []int) {
	return file_control_v1_control_proto_rawDescGZIP(), []int{3}
}

func (x *GetProjectConfigResponse) GetConfig() *ProjectConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *GetProjectConfigResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type Project struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Subdomain     string                 `protobuf:"bytes,3,opt,name=subdomain,proto3" json:"subdomain,omitempty"`
	Plan          string                 `protobuf:"bytes,4,opt,name=plan,proto3" json:"plan,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`                         // active | suspended | deleted
	CreatedAt     int64                  `protobuf:"varint,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // unix seconds
	UpdatedAt     int64                  `protobuf:"varint,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Project) Reset() {
	*x = Project{}
	mi := &file_control_v1_control_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Project) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Project) ProtoMessage() {}

func (x *Project) ProtoReflect() protoreflect.Message {
	mi := &file_control_v1_control_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Project.ProtoReflect.Descriptor instead.
func (*Project) Descriptor() ([]byte, []int) {
	return file_control_v1_control_proto_rawDescGZIP(), []int{4}
}

func (x *Project) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Project) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Project) GetSubdomain() string {
	if x != nil {
		return x.Subdomain
	}
	return ""
}

func (x *Project) GetPlan() string {
	if x != nil {
		return x.Plan
	}
	return ""
}

func (x *Project) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Project) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Project) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type ProjectConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Project       *Project               `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	Entities      []*Entity              `protobuf:"bytes,2,rep,name=entities,proto3" json:"entities,omitempty"`
	Modules       []*Module              `protobuf:"bytes,3,rep,name=modules,proto3" json:"modules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectConfig) Reset() {
	*x = ProjectConfig{}
	mi := &file_control_v1_control_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectConfig) ProtoMessage() {}

func (x *ProjectConfig) ProtoReflect() protoreflect.Message {
	mi := &file_control_v1_control_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectConfig.ProtoReflect.Descriptor instead.
func (*ProjectConfig) Descriptor() ([]byte, []int) {
	return file_control_v1_control_proto_rawDescGZIP(), []int{5}
}

func (x *ProjectConfig) GetProject() *Project {
	if x != nil {
		return x.Project
	}
	return nil
}

func (x *ProjectConfig) GetEntities() []*Entity {
	if x != nil {
		return x.Entities
	}
	return nil
}

func (x *ProjectConfig) GetModules() []*Module {
	if x != nil {
		return x.Modules
	}
	return nil
}

type Entity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Fields        []*Field               `protobuf:"bytes,3,rep,name=fields,proto3" json:"fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Entity) Reset() {
	*x = Entity{}
	mi := &file_control_v1_control_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entity) ProtoMessage() {}

func (x *Entity) ProtoReflect() protoreflect.Message {
	mi := &file_control_v1_control_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entity.ProtoReflect.Descriptor instead.
func (*Entity) Descriptor() ([]byte, []int) {
	return file_control_v1_control_proto_rawDescGZIP(), []int{6}
}

func (x *Entity) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Entity) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Entity) GetFields() []*Field {
	if x != nil {
		return x.Fields
	}
	return nil
}

type Field struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	System        bool                   `protobuf:"varint,4,opt,name=system,proto3" json:"system,omitempty"`
	Unique        bool                   `protobuf:"varint,5,opt,name=unique,proto3" json:"unique,omitempty"`
	EnumValues    []string               `protobuf:"bytes,6,rep,name=enum_values,json=enumValues,proto3" json:"enum_values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Field) Reset() {
	*x = Field{}
	mi := &file_control_v1_control_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Field) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Field) ProtoMessage() {}

func (x *Field) ProtoReflect() protoreflect.Message {
	mi := &file_control_v1_control_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Field.ProtoReflect.Descriptor instead.
func (*Field) Descriptor() ([]byte, []int) {
	return file_control_v1_control_proto_rawDescGZIP(), []int{7}
}

func (x *Field) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Field) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Field) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Field) GetSystem() bool {
	if x != nil {
		return x.System
	}
	return false
}

func (x *Field) GetUnique() bool {
	if x != nil {
		return x.Unique
	}
	return false
}

func (x *Field) GetEnumValues() []string {
	if x != nil {
		return x.EnumValues
	}
	return nil
}

type Module struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"` // auth | crud | storage | ...
	Functions     []*Function            `protobuf:"bytes,3,rep,name=functions,proto3" json:"functions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Module) Reset() {
	*x = Module{}
	mi := &file_control_v1_control_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Module) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Module) ProtoMessage() {}

func (x *Module) ProtoReflect() protoreflect.Message {
	mi := &file_control_v1_control_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Module.ProtoReflect.Descriptor instead.
func (*Module) Descriptor() ([]byte, []int) {
	return file_control_v1_control_proto_rawDescGZIP(), []int{8}
}

func (x *Module) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Module) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Module) GetFunctions() []*Function {
	if x != nil {
		return x.Functions
	}
	return nil
}

type Function struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"` // signup | signin | create | ...
	EnabledFieldIds []string               `protobuf:"bytes,3,rep,name=enabled_field_ids,json=enabledFieldIds,proto3" json:"enabled_field_ids,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Function) Reset() {
	*x = Function{}
	mi := &file_control_v1_control_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Function) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Function) ProtoMessage() {}

func (x *Function) ProtoReflect() protoreflect.Message {
	mi := &file_control_v1_control_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Function.ProtoReflect.Descriptor instead.
func (*Function) Descriptor() ([]byte, []int) {
	return file_control_v1_control_proto_rawDescGZIP(), []int{9}
}

func (x *Function) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Function) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Function) GetEnabledFieldIds() []string {
	if x != nil {
		return x.EnabledFieldIds
	}
	return nil
}

var File_control_v1_control_proto protoreflect.FileDescriptor

const file_control_v1_control_proto_rawDesc = "" +
	"\n" +
	"\x18control/v1/control.proto\x12\n" +
	"control.v1\"2\n" +
	"\x11GetProjectRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\"Y\n" +
	"\x12GetProjectResponse\x12-\n" +
	"\aproject\x18\x01 \x01(\v2\x13.control.v1.ProjectR\aproject\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"8\n" +
	"\x17GetProjectConfigRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\"c\n" +
	"\x18GetProjectConfigResponse\x121\n" +
	"\x06config\x18\x01 \x01(\v2\x19.control.v1.ProjectConfigR\x06config\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\xb5\x01\n" +
	"\aProject\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1c\n" +
	"\tsubdomain\x18\x03 \x01(\tR\tsubdomain\x12\x12\n" +
	"\x04plan\x18\x04 \x01(\tR\x04plan\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\x03R\tupdatedAt\"\x9c\x01\n" +
	"\rProjectConfig\x12-\n" +
	"\aproject\x18\x01 \x01(\v2\x13.control.v1.ProjectR\aproject\x12.\n" +
	"\bentities\x18\x02 \x03(\v2\x12.control.v1.EntityR\bentities\x12,\n" +
	"\amodules\x18\x03 \x03(\v2\x12.control.v1.ModuleR\amodules\"W\n" +
	"\x06Entity\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12)\n" +
	"\x06fields\x18\x03 \x03(\v2\x11.control.v1.FieldR\x06fields\"\x90\x01\n" +
	"\x05Field\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x16\n" +
	"\x06system\x18\x04 \x01(\bR\x06system\x12\x16\n" +
	"\x06unique\x18\x05 \x01(\bR\x06unique\x12\x1f\n" +
	"\venum_values\x18\x06 \x03(\tR\n" +
	"enumValues\"`\n" +
	"\x06Module\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x122\n" +
	"\tfunctions\x18\x03 \x03(\v2\x14.control.v1.FunctionR\tfunctions\"Z\n" +
	"\bFunction\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12*\n" +
	"\x11enabled_field_ids\x18\x03 \x03(\tR\x0fenabledFieldIds2\xc1\x01\n" +
	"\x13ControlPlaneService\x12K\n" +
	"\n" +
	"GetProject\x12\x1d.control.v1.GetProjectRequest\x1a\x1e.control.v1.GetProjectResponse\x12]\n" +
	"\x10GetProjectConfig\x12#.control.v1.GetProjectConfigRequest\x1a$.control.v1.GetProjectConfigResponseB(Z&backify/pkg/proto/control/v1;controlv1b\x06proto3"

var (
	file_control_v1_control_proto_rawDescOnce sync.Once
	file_control_v1_control_proto_rawDescData []byte
)

func file_control_v1_control_proto_rawDescGZIP() []byte {
	file_control_v1_control_proto_rawDescOnce.Do(func() {
		file_control_v1_control_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_control_v1_control_proto_rawDesc), len(file_control_v1_control_proto_rawDesc)))
	})
	return file_control_v1_control_proto_rawDescData
}

var file_control_v1_control_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_control_v1_control_proto_goTypes = []any{
	(*GetProjectRequest)(nil),        // 0: control.v1.GetProjectRequest
	(*GetProjectResponse)(nil),       // 1: control.v1.GetProjectResponse
	(*GetProjectConfigRequest)(nil),  // 2: control.v1.GetProjectConfigRequest
	(*GetProjectConfigResponse)(nil), // 3: control.v1.GetProjectConfigResponse
	(*Project)(nil),                  // 4: control.v1.Project
	(*ProjectConfig)(nil),            // 5: control.v1.ProjectConfig
	(*Entity)(nil),                   // 6: control.v1.Entity
	(*Field)(nil),                    // 7: control.v1.Field
	(*Module)(nil),                   // 8: control.v1.Module
	(*Function)(nil),                 // 9: control.v1.Function
}
var file_control_v1_control_proto_depIdxs = []int32{
	4, // 0: control.v1.GetProjectResponse.project:type_name -> control.v1.Project
	5, // 1: control.v1.GetProjectConfigResponse.config:type_name -> control.v1.ProjectConfig
	4, // 2: control.v1.ProjectConfig.project:type_name -> control.v1.Project
	6, // 3: control.v1.ProjectConfig.entities:type_name -> control.v1.Entity
	8, // 4: control.v1.ProjectConfig.modules:type_name -> control.v1.Module
	7, // 5: control.v1.Entity.fields:type_name -> control.v1.Field
	9, // 6: control.v1.Module.functions:type_name -> control.v1.Function
	0, // 7: control.v1.ControlPlaneService.GetProject:input_type -> control.v1.GetProjectRequest
	2, // 8: control.v1.ControlPlaneService.GetProjectConfig:input_type -> control.v1.GetProjectConfigRequest
	1, // 9: control.v1.ControlPlaneService.GetProject:output_type -> control.v1.GetProjectResponse
	3, // 10: control.v1.ControlPlaneService.GetProjectConfig:output_type -> control.v1.GetProjectConfigResponse
	9, // [9:11] is the sub-list for method output_type
	7, // [7:9] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_control_v1_control_proto_init() }
func file_control_v1_control_proto_init() {
	if File_control_v1_control_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_control_v1_control_proto_rawDesc), len(file_control_v1_control_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_control_v1_control_proto_goTypes,
		DependencyIndexes: file_control_v1_control_proto_depIdxs,
		MessageInfos:      file_control_v1_control_proto_msgTypes,
	}.Build()
	File_control_v1_control_proto = out.File
	file_control_v1_control_proto_goTypes = nil
	file_control_v1_control_proto_depIdxs = nil
}
